let keyshowfullurl=1;const showprivatedata=1;const keyword={companyManagedProject:'company-managed project',https:'https://',servicedesk:'jira/servicedesk',software:'jira/software',secureadmin:'secure/admin',secureadminSD:'secure/admin/SD',servlet:'plugins/servlet',jirasettings:'jira/settings',adminatlassiano:'https://admin.atlassian.com/o',adminatlassians:'https://admin.atlassian.com/s',restApi2:'api'};const clrcommon={fontJiraTopic:'#a0a0a0',fontProjctMngedBy:'#404040',fontSoft:'#f040f0',fontJsm:'#40f040',fontDcSoft:'#c020c0',fontDcJsm:'#20bf20',fontLink:'#e0e0a0',fontSecrAdmn:'#fc2403',fontSecrAdmnSD:'#a0e000',fontServlet:'#0388fc',fontJiraSttngs:'#fc9803',fontAdminatlassiano:'#8c03fc',fontAdminatlassians:'#6203fc',fontRestApi2:'#34d5eb'};const clrsred={bgndpage:'#200000',bgndhdr:'#402020',fonthdr:'#a06060',bordercolor:'#602020'};const clrsblue={bgndpage:'#000020',bgndhdr:'#2020a0',fonthdr:'#6060a0',bordercolor:'#202060'};let clrs;clrs={...clrcommon,...clrsblue};let userCheckedApps=0;const appmap={all:'all',soft:'soft',jsm:'jsm',jwm:'jwm',dcs:'dcs',dcd:'dcd',unmapped:'unmapped'};const printme={companyManagedProject:'cmp',emptyhref:'javascript:void(0)'};function groupSubSetsBySystem(aRawList){const theDistinctListOfDiscoveredGroups=new Map();const theGroupedSubsets=new Map();aRawList.forEach((obj,key)=>{});}
function generateJiraCloudCheatSheet(){const baseUrlUserInput=document.getElementById('inputBoxBaseUrl');let baseUrlCleared=baseUrlUserInput.value.trim();if(!baseUrlCleared||!isValidUrl(baseUrlCleared)){baseUrlCleared="https://brighttunnel.atlassian.net";document.getElementById('inputBoxBaseUrl').value=baseUrlCleared;saveBaseUrlAtLocalStorage('LocalStorageTheBaseUrl',baseUrlCleared);reloadTablels(baseUrlCleared);alert("Enter a valid URL, I’ll push in a default for now =}");return;}
saveBaseUrlAtLocalStorage('LocalStorageTheBaseUrl',baseUrlCleared);reloadTablels(baseUrlCleared);}
function generateTable(aMap,aBaseUrl){const table=document.createElement('table');const thead=document.createElement('thead');const tbody=document.createElement('tbody');const headerRow=document.createElement('tr');let headerarr;switch(keyshowfullurl){case 0:headerarr=['jira cloud topic','gbl','sft','jsm','dc','direct link to the jira service','lnk'];break;case 1:headerarr=['jira cloud topic','gbl','sft','jsm','dc','direct link to the jira service','lnk','full url'];break;case 2:headerarr=['jira cloud topic','gbl','sft','jsm','dc','direct link to the jira service','lnk','topic url','service sub - url '];}
headerarr.forEach(header=>{const th=document.createElement('th');th.textContent=header;headerRow.appendChild(th);});thead.appendChild(headerRow);aMap.forEach((rwobj,rwkey)=>{const row=document.createElement('tr');let rowLinkColor=clrs.fontLink;let linkHasKey="";let fulllink='';if(userCheckedApps&16||userCheckedApps&8&&rwobj.jraAppSft==''&&rwobj.jraAppJsm==''&&rwobj.jraAppDC==''||userCheckedApps&2&&rwobj.jraAppSft||userCheckedApps&4&&rwobj.jraAppJsm||userCheckedApps&1&&rwobj.jraAppDC){if(rwobj.jraLnk.includes(keyword.https)){if(showprivatedata==1){fulllink=rwobj.jraLnk;}else{fulllink=printme.emptyhref;}}else{fulllink=aBaseUrl+"/"+rwobj.jraLnk;}
if(rwobj.jraLnk.includes(keyword.servicedesk)){linkHasKey="sd";rowLinkColor=clrs.fontJsm;}else if(rwobj.jraLnk.includes(keyword.software)){linkHasKey="sft";rowLinkColor=clrs.fontSoft;}else if(rwobj.jraLnk.includes(keyword.servlet)){linkHasKey="srvl";rowLinkColor=clrs.fontServlet;}else if(rwobj.jraLnk.includes(keyword.secureadminSD)){linkHasKey="sasd";rowLinkColor=clrs.fontSecrAdmnSD;}else if(rwobj.jraLnk.includes(keyword.secureadmin)){linkHasKey="adm";rowLinkColor=clrs.fontSecrAdmn;}else if(rwobj.jraLnk.includes(keyword.jirasettings)){linkHasKey="sets";rowLinkColor=clrs.fontJiraSttngs;}else if(rwobj.jraLnk.includes(keyword.adminatlassiano)){linkHasKey="o";rowLinkColor=clrs.fontAdminatlassiano;}else if(rwobj.jraLnk.includes(keyword.adminatlassians)){linkHasKey="s";rowLinkColor=clrs.fontAdminatlassians;}else if(rwobj.jraLnk.includes(keyword.restApi2)){linkHasKey="api";rowLinkColor=clrs.fontRestApi2;}
const cellJraTopic=document.createElement('td');cellJraTopic.textContent=rwobj.jraSub;cellJraTopic.style.textAlign="right";cellJraTopic.style.fontWeight="bold";cellJraTopic.style.color=clrs.fontJiraTopic;cellJraTopic.style.width="260px";const cellGlblPrjct=document.createElement('td');if(rwobj.jraPrjctScp===keyword.companyManagedProject){cellGlblPrjct.textContent=printme.companyManagedProject;}else{cellGlblPrjct.textContent="";}
cellGlblPrjct.style.textAlign="center";cellGlblPrjct.style.color=clrs.fontProjctMngedBy;cellGlblPrjct.style.width="4px";const cellAppSft=document.createElement('td');cellAppSft.textContent=rwobj.jraAppSft;cellAppSft.style.textAlign="center";cellAppSft.style.fontWeight="bold";cellAppSft.style.width="4px";cellAppSft.style.color=clrs.fontSoft;const cellAppJsm=document.createElement('td');cellAppJsm.textContent=rwobj.jraAppJsm;cellAppJsm.style.textAlign="center";cellAppJsm.style.fontWeight="bold";cellAppJsm.style.width="4px";cellAppJsm.style.color=clrs.fontJsm;const cellAppDc=document.createElement('td');cellAppDc.textContent=rwobj.jraAppDC;cellAppDc.style.textAlign="center";cellAppDc.style.fontWeight="bold";cellAppDc.style.width="4px";if(rwobj.jraAppDC==appmap.dcs){cellAppDc.style.color=clrs.fontDcSoft;}else{cellAppDc.style.color=clrs.rowLinkColor;}
const linkElement=document.createElement('a');linkElement.textContent=rwobj.jraSrvc;linkElement.href=fulllink;linkElement.target="_blank";linkElement.style.fontWeight="bold";linkElement.style.color=rowLinkColor;const cellJraServiceLink=document.createElement('td');cellJraServiceLink.innerHTML=linkElement.outerHTML;cellJraServiceLink.style.width="290px";const celllinktype=document.createElement('td');celllinktype.textContent=linkHasKey;celllinktype.style.textAlign="center";celllinktype.style.fontWeight="bold";celllinktype.style.width="4px";celllinktype.style.color=rowLinkColor;const cellJraSubUrl=document.createElement('td');const stableLeftSubUrl=exctractLinkSubRoot(rwobj.jraLnk);cellJraSubUrl.textContent=stableLeftSubUrl;cellJraSubUrl.style.textAlign="left";cellJraSubUrl.style.width="360px";const cellJraFullSubUrl=document.createElement('td');cellJraFullSubUrl.textContent=`${rwobj.jraLnk}`.substring(stableLeftSubUrl.length+1);cellJraFullSubUrl.style.textAlign="left";cellJraFullSubUrl.style.width="670px";cellJraFullSubUrl.style.color=rowLinkColor;const cellJraFullUrl=document.createElement('td');cellJraFullUrl.textContent=fulllink;cellJraFullUrl.style.textAlign="left";cellJraFullUrl.style.width="1020px";row.appendChild(cellJraTopic);row.appendChild(cellGlblPrjct);row.appendChild(cellAppSft);row.appendChild(cellAppJsm);row.appendChild(cellAppDc);row.appendChild(cellJraServiceLink);row.appendChild(celllinktype);switch(keyshowfullurl){case 0:break;case 1:row.appendChild(cellJraFullUrl);break;case 2:row.appendChild(cellJraSubUrl);row.appendChild(cellJraFullSubUrl);}
tbody.appendChild(row);}});table.appendChild(thead);table.appendChild(tbody);return table;}
function reloadTablels(savedBaseUrl){const tablecontainervar=document.getElementById('tablecontainerid');tablecontainervar.innerHTML='';const groupedUsers=groupByKey(rd,'jraSctn');groupedUsers.forEach((value,key)=>{tablecontainervar.innerHTML+="<h2 style='color:#e00000;'>"+`${key}`+"</h2>";tablecontainervar.appendChild(generateTable(value,savedBaseUrl));});}
function groupByKey(array,key){const map=new Map();array.forEach(item=>{const keyValue=item[key];if(!map.has(keyValue)){map.set(keyValue,[]);}
map.get(keyValue).push(item);});return map;}
function isValidUrl(url){try{new URL(url);return true;}catch(_){return false;}}
function exctractLinkSubRoot(url){if(url){const linkElements=url.split("/");const lng="";let reslt="";for(let ii=0;ii<linkElements.length-1;ii++){reslt+=linkElements[ii]+"/";}
return reslt.substring(0,reslt.length-1);}else{return"";}}
function saveBaseUrlAtLocalStorage(aKey,aValue){localStorage.setItem(aKey,aValue);}
function readBaseUrlFromLocalStorage(aKey){const savedBaseUrl=localStorage.getItem(aKey);if(!savedBaseUrl){savedBaseUrl="https://brighttunnel.atlassian.net";}
document.getElementById('inputBoxBaseUrl').value=savedBaseUrl;return savedBaseUrl;}
